//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCalDocked.Localize {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iCalDocked.Localize.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1st に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2nd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3rd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   th に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DayOther {
            get {
                return ResourceManager.GetString("DayOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ddd, MMM d に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DayViewTitleFormat {
            get {
                return ResourceManager.GetString("DayViewTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DOW1 {
            get {
                return ResourceManager.GetString("DOW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DOW2 {
            get {
                return ResourceManager.GetString("DOW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DOW3 {
            get {
                return ResourceManager.GetString("DOW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DOW4 {
            get {
                return ResourceManager.GetString("DOW4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DOW5 {
            get {
                return ResourceManager.GetString("DOW5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DOW6 {
            get {
                return ResourceManager.GetString("DOW6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DOW7 {
            get {
                return ResourceManager.GetString("DOW7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMM yyyy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthViewTitleFormat {
            get {
                return ResourceManager.GetString("MonthViewTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YearViewMonthFormat {
            get {
                return ResourceManager.GetString("YearViewMonthFormat", resourceCulture);
            }
        }
    }
}
