// Copyright 2011 Miyako Komooka
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCalSettings.Localize {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iCalSettings.Localize.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Choose.. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   help.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpFile {
            get {
                return ResourceManager.GetString("HelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calendar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1_Calendar {
            get {
                return ResourceManager.GetString("Tab1_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iCalendar File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_CalendarFile {
            get {
                return ResourceManager.GetString("Tab1Item_CalendarFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_Clear {
            get {
                return ResourceManager.GetString("Tab1Item_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_ConnectionTest {
            get {
                return ResourceManager.GetString("Tab1Item_ConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday Calendar: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_HolidayCalendar {
            get {
                return ResourceManager.GetString("Tab1Item_HolidayCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iCalendar File for Holiday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_HolidayFile {
            get {
                return ResourceManager.GetString("Tab1Item_HolidayFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Calendar: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_NormalCalendar {
            get {
                return ResourceManager.GetString("Tab1Item_NormalCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_Password {
            get {
                return ResourceManager.GetString("Tab1Item_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab1Item_UserID {
            get {
                return ResourceManager.GetString("Tab1Item_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2_View {
            get {
                return ResourceManager.GetString("Tab2_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_BackgroundColor {
            get {
                return ResourceManager.GetString("Tab2Item_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_DayBackground {
            get {
                return ResourceManager.GetString("Tab2Item_DayBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_DayBold {
            get {
                return ResourceManager.GetString("Tab2Item_DayBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_DayForeground {
            get {
                return ResourceManager.GetString("Tab2Item_DayForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Days: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_Days {
            get {
                return ResourceManager.GetString("Tab2Item_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underline: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_DayUnderline {
            get {
                return ResourceManager.GetString("Tab2Item_DayUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_EventDay {
            get {
                return ResourceManager.GetString("Tab2Item_EventDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icons: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_Icons {
            get {
                return ResourceManager.GetString("Tab2Item_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_NormalDay {
            get {
                return ResourceManager.GetString("Tab2Item_NormalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_Today {
            get {
                return ResourceManager.GetString("Tab2Item_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Todo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab2Item_TodoDay {
            get {
                return ResourceManager.GetString("Tab2Item_TodoDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Others に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3_Others {
            get {
                return ResourceManager.GetString("Tab3_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arguments: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_Arguments {
            get {
                return ResourceManager.GetString("Tab3Item_Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day View Title Format: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_DVTitle {
            get {
                return ResourceManager.GetString("Tab3Item_DVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command when events or todos selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_EventAction {
            get {
                return ResourceManager.GetString("Tab3Item_EventAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * URL(http://..) or Command(*.exe etc.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_HttpAllowed {
            get {
                return ResourceManager.GetString("Tab3Item_HttpAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload interval of calendars: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_Interval {
            get {
                return ResourceManager.GetString("Tab3Item_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * $Y-Year $M-Month $D-Day $U-UID $$-$ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_MiniHelp {
            get {
                return ResourceManager.GetString("Tab3Item_MiniHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_Minute {
            get {
                return ResourceManager.GetString("Tab3Item_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month View Title Format: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tab3Item_MVTitle {
            get {
                return ResourceManager.GetString("Tab3Item_MVTitle", resourceCulture);
            }
        }
    }
}
